### ISSUE TITLE
docker-compose build failed on git-nbdiffdriver

### ISSUE THREAD

**Issue by rpranata** [ageron/handson-ml2#113]
## Reproduction Step

1. A clean environment 
1. Follow the steps to prepare the `handson-ml2` image from the [docker setup readme](https://github.com/ageron/handson-ml2/tree/master/docker#prepare-the-image-once)

## Expected

The `handson-ml2` docker image is created

## Actual

Failed when building due to an attempt to import from `gitdb.util.compat` module. 

```
Step 15/18 : RUN git-nbdiffdriver config --enable --global
 ---> Running in d15cbb46ac68
Traceback (most recent call last):
  File "/opt/conda/envs/tf2/bin/git-nbdiffdriver", line 7, in <module>
    from nbdime.vcs.git.diffdriver import main
  File "/opt/conda/envs/tf2/lib/python3.7/site-packages/nbdime/vcs/git/diffdriver.py", line 26, in <module>
    from nbdime.args import (
  File "/opt/conda/envs/tf2/lib/python3.7/site-packages/nbdime/args.py", line 18, in <module>
    from .gitfiles import is_gitref
  File "/opt/conda/envs/tf2/lib/python3.7/site-packages/nbdime/gitfiles.py", line 11, in <module>
    from git import (
  File "/opt/conda/envs/tf2/lib/python3.7/site-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/opt/conda/envs/tf2/lib/python3.7/site-packages/git/exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "/opt/conda/envs/tf2/lib/python3.7/site-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ModuleNotFoundError: No module named 'gitdb.utils.compat'
ERROR: Service 'handson-ml2' failed to build: The command '/bin/sh -c git-nbdiffdriver config --enable --global' returned a non-zero code: 1
```

Further investigation led me to believe that the `compat` module [has been removed](https://github.com/gitpython-developers/gitdb/commit/db9a65e3b0eceb9c52359273afb3313860e5e322) in gitdb version `3.0.2`. 

The `gitdb` is a resolved dependency chain as below
- [`handson-ml2`](https://github.com/ageron/handson-ml2/blob/master/environment.yml#L13)
- [`nbdime`](https://github.com/jupyter/nbdime/blob/master/setup.py#L117)
- [`GitPython`](https://github.com/gitpython-developers/GitPython/commit/e81fd5447f8800373903e024122d034d74a273f7)

**Comment by Harmon758** [comment]
See https://github.com/gitpython-developers/GitPython/issues/983.

**Comment by rpranata** [comment]
Thank you @Harmon758. 

It works after I [explicitly](https://github.com/ageron/handson-ml2/compare/master...rpranata:update-git-python?expand=1) added `GitPython` dependency with the latest version into the `environment.yml`
