### ISSUE TITLE
set environment error

### ISSUE THREAD

**Issue by 7568** [ageron/handson-ml2#184]
Hi , this is my problem
when i run the command ` conda env create -f environment.yml ` , it can load package , but throw exception in the end

> Downloading and Extracting Packages
> harfbuzz-1.8.8       | 414 KB    | ####################### | 100%
> .....
> entrypoints-0.3      | 12 KB     | ######################## | 100% 
> bzip2-1.0.8          | 75 KB     | ######################### | 100% 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> Ran pip subprocess with arguments:
> ['/opt/miniconda3/envs/tf2/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/louis/Documents/git/handson-ml2/condaenv.zvsrfesn.requirements.txt']
> Pip subprocess output:
> Collecting atari-py==0.2.6
>   Downloading atari_py-0.2.6-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.5 MB)
> 
> Pip subprocess error:
> ERROR: Exception:
> Traceback (most recent call last):
>   File "/opt/miniconda3/envs/tf2/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 313, in recv_into
>     return self.connection.recv_into(*args, **kwargs)
>   File "/opt/miniconda3/envs/tf2/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1840, in recv_into
>     self._raise_ssl_error(self._ssl, result)
>   File "/opt/miniconda3/envs/tf2/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1646, in _raise_ssl_error
>     raise WantReadError()
> OpenSSL.SSL.WantReadError

i thought the reason is i have not the file '**condaenv.zvsrfesn.requirements.txt**' , in my 'handson-ml2' folder , only have the file **requirements.txt.** 

I found the same problem in this page 'https://github.com/ageron/handson-ml2/issues/92' , but i still don't know how to solve it

**Comment by 7568** [comment]
after i down load laster version ,I have a new error 

> handson-ml2 git:(master) ✗ conda env create -f environment.yml
> Collecting package metadata (repodata.json): failed
> 
> # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> 
>     Traceback (most recent call last):
>       File "/opt/miniconda3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 313, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "/opt/miniconda3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1840, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "/opt/miniconda3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1646, in _raise_ssl_error
>         raise WantReadError()
>     OpenSSL.SSL.WantReadError
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "/opt/miniconda3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 313, in recv_into
>         return self.connection.recv_into(*args, **kwargs)
>       File "/opt/miniconda3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1840, in recv_into
>         self._raise_ssl_error(self._ssl, result)
>       File "/opt/miniconda3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1663, in _raise_ssl_error
>         raise SysCallError(errno, errorcode.get(errno))
>     OpenSSL.SSL.SysCallError: (54, 'ECONNRESET')
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "/opt/miniconda3/lib/python3.7/site-packages/urllib3/response.py", line 425, in _error_catcher
>         yield
>       File "/opt/miniconda3/lib/python3.7/site-packages/urllib3/response.py", line 752, in read_chunked
>         self._update_chunk_length()
>       File "/opt/miniconda3/lib/python3.7/site-packages/urllib3/response.py", line 682, in _update_chunk_length
>         line = self._fp.fp.readline()
>       File "/opt/miniconda3/lib/python3.7/socket.py", line 589, in readinto
>         return self._sock.recv_into(b)
>       File "/opt/miniconda3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 328, in recv_into
>         return self.recv_into(*args, **kwargs)
>       File "/opt/miniconda3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 318, in recv_into
>         raise SocketError(str(e))
>     OSError: (54, 'ECONNRESET')
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "/opt/miniconda3/lib/python3.7/site-packages/requests/models.py", line 751, in generate
>         for chunk in self.raw.stream(chunk_size, decode_content=True):
>       File "/opt/miniconda3/lib/python3.7/site-packages/urllib3/response.py", line 560, in stream
>         for line in self.read_chunked(amt, decode_content=decode_content):
>       File "/opt/miniconda3/lib/python3.7/site-packages/urllib3/response.py", line 781, in read_chunked
>         self._original_response.close()
>       File "/opt/miniconda3/lib/python3.7/contextlib.py", line 130, in __exit__
>         self.gen.throw(type, value, traceback)
>       File "/opt/miniconda3/lib/python3.7/site-packages/urllib3/response.py", line 443, in _error_catcher
>         raise ProtocolError("Connection broken: %r" % e, e)
>     urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(54, \'ECONNRESET\')")', OSError("(54, 'ECONNRESET')"))
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
>         return func(*args, **kwargs)
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
>         exit_code = getattr(module, func_name)(args, parser)
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 111, in execute
>         result[installer_type] = installer.install(prefix, pkg_specs, args, env)
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda_env/installers/conda.py", line 32, in install
>         prune=getattr(args, 'prune', False), update_modifier=UpdateModifier.FREEZE_INSTALLED)
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
>         should_retry_solve)
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
>         force_remove, should_retry_solve)
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
>         ssc = self._collect_all_metadata(ssc)
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
>         return f(*args, **kwds)
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 415, in _collect_all_metadata
>         index, r = self._prepare(prepared_specs)
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 1011, in _prepare
>         self.subdirs, prepared_specs, self._repodata_fn)
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 228, in get_reduced_index
>         repodata_fn=repodata_fn)
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 105, in query_all
>         result = tuple(concat(executor.map(subdir_query, channel_urls)))
>       File "/opt/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
>         yield fs.pop().result()
>       File "/opt/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
>         return self.__get_result()
>       File "/opt/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
>         raise self._exception
>       File "/opt/miniconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>         result = self.fn(*self.args, **self.kwargs)
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 98, in <lambda>
>         package_ref_or_match_spec))
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 110, in query
>         self.load()
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 174, in load
>         _internal_state = self._load()
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 248, in _load
>         repodata_fn=self.repodata_fn)
>       File "/opt/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 485, in fetch_repodata_remote_request
>         timeout=timeout)
>       File "/opt/miniconda3/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
>         return self.request('GET', url, **kwargs)
>       File "/opt/miniconda3/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
>         resp = self.send(prep, **send_kwargs)
>       File "/opt/miniconda3/lib/python3.7/site-packages/requests/sessions.py", line 683, in send
>         r.content
>       File "/opt/miniconda3/lib/python3.7/site-packages/requests/models.py", line 829, in content
>         self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
>       File "/opt/miniconda3/lib/python3.7/site-packages/requests/models.py", line 754, in generate
>         raise ChunkedEncodingError(e)
>     requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(54, \'ECONNRESET\')")', OSError("(54, 'ECONNRESET')"))
> 
> `$ /opt/miniconda3/bin/conda-env create -f environment.yml`
> 
>   environment variables:
>                  CIO_TEST=<not set>
>   CONDA_AUTO_UPDATE_CONDA=false
>                CONDA_ROOT=/opt/miniconda3
>                      PATH=/opt/miniconda3/bin:/usr/local/opt/openssl/bin:/usr/local/bin:/usr/bin
>                           :/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/salt/bin:/usr/local/sbin:
>                           /Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applicat
>                           ions/Wireshark.app/Contents/MacOS
>        REQUESTS_CA_BUNDLE=<not set>
>             SSL_CERT_FILE=<not set>
> 
>      active environment : None
>        user config file : /Users/louis/.condarc
>  populated config files : /Users/louis/.condarc
>           conda version : 4.8.3
>     conda-build version : not installed
>          python version : 3.7.7.final.0
>        virtual packages : __osx=10.14.4
>        base environment : /opt/miniconda3  (writable)
>            channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/osx-64
>                           https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
>                           https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-64
>                           https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
>           package cache : /opt/miniconda3/pkgs
>                           /Users/louis/.conda/pkgs
>        envs directories : /opt/miniconda3/envs
>                           /Users/louis/.conda/envs
>                platform : osx-64
>              user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Darwin/18.5.0 OSX/10.14.4
>                 UID:GID : 501:20
>              netrc file : None
>            offline mode : False
> 
> 
> An unexpected error has occurred. Conda has prepared the above report.
> 
> Upload did not complete.
