### ISSUE TITLE
 conda env create -f environment.yml fails

### ISSUE THREAD

**Issue by jcatanza** [ageron/handson-ml2#412]
Thanks for helping us improve this project!

**Before you create this issue**
Please make sure you are using the latest updated code and libraries: see https://github.com/ageron/handson-ml2/blob/master/INSTALL.md#update-this-project-and-its-libraries

Also please make sure to read the FAQ (https://github.com/ageron/handson-ml2#faq) and search for existing issues (both open and closed), as your question may already have been answered: https://github.com/ageron/handson-ml2/issues

**Describe the bug**
Please provide a clear and concise description of what the bug is, and specify the notebook name and the cell number at which the problem occurs (or the chapter and page in the book).

**To Reproduce**
Please copy the code that fails here, using code blocks like this:

```python
def inverse(x):
    return 1 / x

result = inverse(0)
```

And if you got an exception, please copy the full stacktrace here:

```stacktrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in inverse
ZeroDivisionError: division by zero
```

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. MacOSX 10.15.7]
 - Python: [e.g. 3.7]
 - TensorFlow: [e.g., 2.4.1]
 - Scikit-Learn: [e.g., 0.24.1]
- Other libraries that may be connected with the issue: [e.g., gym 0.18.0]

**Additional context**

**Comment by jcatanza** [comment]
After a fresh install of anaconda, on WIndows 10 64-bit OS,
I tried to create the environment tf2, but the process failed with 
ERROR conda.core.link:_execute(698): An error occurred while installing package 'conda-forge::qt-5.12.9-h5909a2a_4'.

(base) PS C:\Users\cross-entropy\hands-on-ml2-geron-repo> conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: / Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok

done
ERROR conda.core.link:_execute(698): An error occurred while installing package 'conda-forge::qt-5.12.9-h5909a2a_4'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::qt-5.12.9-h5909a2a_4
location of failed script: C:\Users\cross-entropy\anaconda3\envs\tf2\Scripts\.qt-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:         1 file(s) copied.

stderr: 'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.

return code: 1

()

**Comment by ageron** [comment]
Thanks for your feedback. I don't have Windows, so it's hard for me to test this. Could you please try the solutions proposed in the answers to this [StackOverflow question](https://stackoverflow.com/questions/47614437/unable-to-activate-conda-environment-as-chcp-and-cmd-is-not-recognized-as-in)? It looks like this is a problem with the `PATH` environment variable.

When installing Anaconda on Windows, did you check the option to update your `PATH`? I think it is not recommended as it may mess with some system commands, and this may be what's happening now. Perhaps this would explain the issue. If so, I suggest you uninstall Anaconda and reinstall it *without* checking this option?

If none of this works, I'll rent a Windows Virtual Machine on the cloud to try it out. I did this a few weeks ago, and I didn't have any issue, but I had *not* selected the option to update the `PATH` variable, so this may be the reason.

**Comment by jcatanza** [comment]
Hi Aurelien, thanks for the quick reply.
I did not check the option to update PATH as it was recommended to not do
so.
I've re-installed Anaconda, installed the latest nvidia driver.
Currently trying to install the CUDA and cuDNN libraries, before creating
the tf2 environment.

Cheers,
Joseph

**Comment by ageron** [comment]
I rented a Windows VM, I installed Miniconda, I opened up an Anaconda prompt from the Start menu, I updated `conda` using `conda update -c defaults -n base conda`, then I downloaded the latest `environment.yml` from this project, and I ran `conda env create -f environment.yml`. Everything worked fine, so I'm not sure where the problem comes from.

<img width="1014" alt="Screenshot 2021-03-29 at 11 26 08" src="https://user-images.githubusercontent.com/76661/112770168-e3164300-9081-11eb-80fc-7e16e130fa6a.png">

Are you using an Anaconda prompt? Or an Anaconda Powershell? Or some other terminal?

My `PATH` environment variable is equal to this:

```
C:\Users\ageron\miniconda3;C:\Users\ageron\miniconda3\Library\mingw-w64\bin;C:\Users\ageron\miniconda3\Library\usr\bin;C:\Users\ageron\miniconda3\Library\bin;C:\Users\ageron\miniconda3\Scripts;C:\Users\ageron\miniconda3\bin;C:\Users\ageron\miniconda3\condabin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\ProgramData\GooGet;C:\Program Files\Google\Compute Engine\metadata_scripts;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\PowerShell\7;C:\Program Files\Google\Compute Engine\sysprep;C:\Program Files\Git\cmd;C:\Users\ageron\AppData\Local\Microsoft\WindowsApps;.
```

**Comment by ageron** [comment]
I just tested this installation a bit, it seems to work fine. Even gym works great (it used to be a big pain to install it on Windows with support for Atari environments):

<img width="782" alt="Screenshot 2021-03-29 at 12 16 34" src="https://user-images.githubusercontent.com/76661/112771564-e9f48400-9088-11eb-86bf-7c6192601d5e.png">
