### ISSUE TITLE
16_nlp_with_rnns_and_attention.ipynb cell #18

### ISSUE THREAD

**Issue by sulu987** [ageron/handson-ml2#439]
Thanks for helping us improve this project!

**Before you create this issue**
Please make sure you are using the latest updated code and libraries: see https://github.com/ageron/handson-ml2/blob/master/INSTALL.md#update-this-project-and-its-libraries

Also please make sure to read the FAQ (https://github.com/ageron/handson-ml2#faq) and search for existing issues (both open and closed), as your question may already have been answered: https://github.com/ageron/handson-ml2/issues

**Describe what is unclear to you**
Please provide a clear and concise description of what the problem is, and specify the notebook name and the cell number at which the problem occurs (or the chapter and page in the book).

**To Reproduce**
If the question relates to a specific piece of code, please copy the code that fails here, using code blocks like this:

```python
def inverse(x):
    return 1 / x

result = inverse(0)
```

And if you get an exception, please copy the full stacktrace here:

```stacktrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in inverse
ZeroDivisionError: division by zero
```

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. MacOSX 10.15.7]
 - Python: [e.g. 3.7]
 - TensorFlow: [e.g., 2.4.1]
 - Scikit-Learn: [e.g., 0.24.1]
- Other libraries that may be connected with the issue: [e.g., gym 0.18.0]

**Additional context**

**Comment by ageron** [comment]
Hi @sulu987 ,

I cannot reproduce this issue, everything works fine on my system and [on Colab](https://colab.research.google.com/github/ageron/handson-ml2/blob/master/16_nlp_with_rnns_and_attention.ipynb).

Questions:
* Are you running on Colab? Or Kaggle? Or your own system?
* If it's on your own system, are you running the most recent notebook version?
* If it's on your own system, what version of TensorFlow are you using?
* Have you made any modification to the code?
* Have you run the cells in order?

**Edit**: it looks like this may be linked to [TensorFlow issue #9706](https://github.com/tensorflow/models/issues/9706) when using Python 3.8. One workaround is to use Python 3.7 instead.

**Comment by sulu987** [comment]
I got it running - thanks for supporting your readers

**Comment by ageron** [comment]
Hi @sulu987 ,
I'm glad things work now! Could you please explain what fixed the issue, in case others run into the same issue?
Thanks!

**Comment by hafiz031** [comment]
I am facing a similar issue: https://stackoverflow.com/q/69320194/6907424. I ran it locally. I have mentioned the packages installed on my machine.

**Comment by ageron** [comment]
Hi @hafiz031 ,
I've tried to reproduce this issue, but the code just works fine. Here's a [notebook containing your StackOverflow code example](https://colab.research.google.com/gist/ageron/4d1129328dacd677972efc72d3470d5a/homl2-issue-439.ipynb) (I just added a couple extra cells to do the imports and create a fake dataset, and I replaced `lr` with `learning_rate` as `lr` is deprecated), and it runs without a problem. Could you please check that `X_train`, `y_train`, `X_valid` and `y_valid` are regular NumPy arrays or concrete tensors (containing actual values), not symbolic tensors?

**Comment by hafiz031** [comment]
@ageron I have printed the types of the respective variables and all of them are `<class 'numpy.ndarray'>`. Another observation is when the `CPU` version of `Tensorflow` is used (in my local machine) the code runs perfectly. It creates problem when I use the `GPU` version.

**Comment by shanemkm** [comment]
@ageron et al: FYI I hit the same error but with Chapter 15 trying to initialize the SimpleRNN as part of the "Using a Simple RNN" section. I'm running on Windows with an Anaconda + VSCode setup, tensorflow 2.3.0 and before the "fix" numpy 1.21.2. The full conda list output for what I have after the fix is [here](https://github.com/ageron/handson-ml2/files/8384717/conda_list_output.txt); I unfortunately didn't save the full list before the fix but it _seems_ like it only messed with numpy and numpy-base.

The "fix" was forcing numpy 1.19.5 via "pip install numpy==1.19.5" in the Anaconda environment window, it's been working for a while and various other notebooks seem to go through fully fine as well, so I can't find any side effects yet, but it does seem like a hacky fix...but hopefully less hacky than some of the stuff listed at https://github.com/tensorflow/models/issues/9706 with editing *\tensorflow\python\ops\array_ops.py. ; )[](url)
