### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tms988** [ageron/handson-ml2#504]
Thanks for helping us improve this project!

**Before you create this issue**
Please make sure you are using the latest updated code and libraries: see https://github.com/ageron/handson-ml2/blob/master/INSTALL.md#update-this-project-and-its-libraries

Also please make sure to read the FAQ (https://github.com/ageron/handson-ml2#faq) and search for existing issues (both open and closed), as your question may already have been answered: https://github.com/ageron/handson-ml2/issues

**Describe the bug**
I typed "conda env create -f environment.yml " in cmd, the results are as shown below. What should I do next? Please teach me.

**To Reproduce**
Please copy the code that fails here, using code blocks like this:

```python
$ handson-ml2-master  conda env create -f environment.yml 
 Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

Downloading and Extracting Packages
prometheus_client-0. | 47 KB     | ########## | 100%
libtiff-4.3.0        | 1.1 MB    | ########## | 100%
libwebp-base-1.2.1   | 393 KB    | ########## | 100%
nest-asyncio-1.5.1   | 9 KB      | ########## | 100%
jupyterlab_pygments- | 8 KB      | ########## | 100%
attrs-20.3.0         | 41 KB     | ########## | 100%
xorg-libxdmcp-1.1.3  | 66 KB     | ########## | 100%
pcre-8.45            | 518 KB    | ########## | 100%
libxgboost-1.4.2     | 2.1 MB    | ########## | 100%
jupyter-1.0.0        | 6 KB      | ########## | 100%
urllib3-1.26.7       | 100 KB    | ########## | 100%
libiconv-1.16        | 680 KB    | ########## | 100%
chardet-4.0.0        | 215 KB    | ########## | 100%
tornado-6.1          | 653 KB    | ########## | 100%
liblapack-3.9.0      | 4.5 MB    | ########## | 100%
libsodium-1.0.18     | 697 KB    | ########## | 100%
webencodings-0.5.1   | 12 KB     | ########## | 100%
xorg-xproto-7.0.31   | 74 KB     | ########## | 100%
lcms2-2.12           | 882 KB    | ########## | 100%
jupyter_client-7.0.6 | 87 KB     | ########## | 100%
lz4-c-1.9.3          | 135 KB    | ########## | 100%
xorg-libx11-1.7.2    | 966 KB    | ########## | 100%
freeglut-3.2.1       | 149 KB    | ########## | 100%
pyqt5-sip-4.19.18    | 299 KB    | ########## | 100%
typing-extensions-3. | 8 KB      | ########## | 100%
backports-1.0        | 4 KB      | ########## | 100%
box2d-py-2.3.8       | 503 KB    | ########## | 100%
async_generator-1.10 | 18 KB     | ########## | 100%
pytz-2021.3          | 242 KB    | ########## | 100%
pyopengl-3.1.5       | 854 KB    | ########## | 100%
qtconsole-5.2.0      | 90 KB     | ########## | 100%
gitpython-3.1.24     | 122 KB    | ########## | 100%
cycler-0.11.0        | 10 KB     | ########## | 100%
nbconvert-6.3.0      | 607 KB    | ########## | 100%
cryptography-35.0.0  | 1.1 MB    | ########## | 100%
joblib-0.14.1        | 198 KB    | ########## | 100%
python-3.8.12        | 19.2 MB   | ########## | 100%
wheel-0.37.0         | 31 KB     | ########## | 100%
python-graphviz-0.18 | 30 KB     | ########## | 100%
libxml2-2.9.12       | 3.4 MB    | ########## | 100%
jupyter_console-6.4. | 22 KB     | ########## | 100%
xorg-libsm-1.2.3     | 96 KB     | ########## | 100%
libopencv-4.5.3      | 46.8 MB   | ########## | 100%
backcall-0.2.0       | 13 KB     | ########## | 100%
entrypoints-0.3      | 8 KB      | ########## | 100%
pywin32-302          | 6.9 MB    | ########## | 100%
libglib-2.70.1       | 3.0 MB    | ########## | 100%
packaging-20.9       | 35 KB     | ########## | 100%
colorama-0.4.4       | 18 KB     | ########## | 100%
ipywidgets-7.6.5     | 101 KB    | ########## | 100%
xorg-kbproto-1.0.7   | 28 KB     | ########## | 100%
typing_extensions-3. | 25 KB     | ########## | 100%
defusedxml-0.7.1     | 23 KB     | ########## | 100%
ffmpeg-4.3.1         | 26.2 MB   | ########## | 100%
pyopenssl-21.0.0     | 48 KB     | ########## | 100%
pip-21.3.1           | 1.2 MB    | ########## | 100%
decorator-5.1.0      | 11 KB     | ########## | 100%
python-dateutil-2.8. | 240 KB    | ########## | 100%
pygments-2.10.0      | 760 KB    | ########## | 100%
m2w64-libwinpthread- | 31 KB     | ########## | 100%
matplotlib-base-3.4. | 7.2 MB    | ########## | 100%
libcblas-3.9.0       | 4.5 MB    | ########## | 100%
nltk-3.6.5           | 1.1 MB    | ########## | 100%
zstd-1.5.0           | 1004 KB   | ########## | 100%
regex-2021.11.10     | 353 KB    | ########## | 100%
olefile-0.46         | 32 KB     | ########## | 100%
jupyter_core-4.9.1   | 104 KB    | ########## | 100%
matplotlib-3.4.3     | 8 KB      | ########## | 100%
openssl-1.1.1l       | 5.7 MB    | ########## | 100%
nbdime-3.1.1         | 4.4 MB    | ########## | 100%
widgetsnbextension-3 | 1.3 MB    | ########## | 100%
charset-normalizer-2 | 32 KB     | ########## | 100%
numexpr-2.7.3        | 132 KB    | ########## | 100%
jupyter-server-mathj | 2.3 MB    | ########## | 100%
jsonschema-4.2.1     | 118 KB    | ########## | 100%
notebook-6.4.6       | 6.2 MB    | ########## | 100%
mistune-0.8.4        | 55 KB     | ########## | 100%
font-ttf-dejavu-sans | 388 KB    | ########## | 100%
win_inet_pton-1.1.0  | 9 KB      | ########## | 100%
_py-xgboost-mutex-2. | 11 KB     | ########## | 100%
opencv-4.5.3         | 22 KB     | ########## | 100%
libffi-3.4.2         | 41 KB     | ########## | 100%
prompt_toolkit-3.0.2 | 5 KB      | ########## | 100%
expat-2.4.1          | 279 KB    | ########## | 100%
parso-0.8.2          | 68 KB     | ########## | 100%
fonts-conda-ecosyste | 4 KB      | ########## | 100%
icu-68.2             | 16.4 MB   | ########## | 100%
libzlib-1.2.11       | 63 KB     | ########## | 100%
jbig-2.1             | 45 KB     | ########## | 100%
pandocfilters-1.5.0  | 11 KB     | ########## | 100%
intel-openmp-2021.4. | 3.2 MB    | ########## | 100%
pyparsing-3.0.6      | 79 KB     | ########## | 100%
pthread-stubs-0.4    | 6 KB      | ########## | 100%
pycparser-2.21       | 100 KB    | ########## | 100%
py-opencv-4.5.3      | 24 KB     | ########## | 100%
zlib-1.2.11          | 106 KB    | ########## | 100%
certifi-2021.10.8    | 145 KB    | ########## | 100%
winpty-0.4.3         | 1.1 MB    | ########## | 100%
xorg-libxext-1.3.4   | 282 KB    | ########## | 100%
scikit-learn-1.0.1   | 6.9 MB    | ########## | 100%
pickleshare-0.7.5    | 9 KB      | ########## | 100%
xorg-libice-1.0.10   | 181 KB    | ########## | 100%
pyqtwebengine-5.12.1 | 143 KB    | ########## | 100%
nbclient-0.5.8       | 64 KB     | ########## | 100%
xorg-libxpm-3.5.13   | 236 KB    | ########## | 100%
libdeflate-1.8       | 61 KB     | ########## | 100%
terminado-0.12.1     | 28 KB     | ########## | 100%
pango-1.48.10        | 735 KB    | ########## | 100%
pillow-8.3.2         | 776 KB    | ########## | 100%
qtpy-1.11.2          | 37 KB     | ########## | 100%
argon2-cffi-21.1.0   | 50 KB     | ########## | 100%
freetype-2.10.4      | 489 KB    | ########## | 100%
ipython-7.28.0       | 1.2 MB    | ########## | 100%
graphite2-1.3.13     | 97 KB     | ########## | 100%
click-7.1.2          | 64 KB     | ########## | 100%
fontconfig-2.13.1    | 1.7 MB    | ########## | 100%
fonts-conda-forge-1  | 4 KB      | ########## | 100%
libwebp-1.2.1        | 11 KB     | ########## | 100%
xorg-xextproto-7.3.0 | 28 KB     | ########## | 100%
jupyter_server-1.11. | 257 KB    | ########## | 100%
zeromq-4.3.4         | 8.9 MB    | ########## | 100%
getopt-win32-0.1     | 19 KB     | ########## | 100%
brotlipy-0.7.0       | 369 KB    | ########## | 100%
pyqt-impl-5.12.3     | 4.3 MB    | ########## | 100%
sniffio-1.2.0        | 16 KB     | ########## | 100%
mkl-2021.4.0         | 181.7 MB  | ########## | 100%
libxcb-1.13          | 1.3 MB    | ########## | 100%
markupsafe-2.0.1     | 25 KB     | ########## | 100%
xz-5.2.5             | 211 KB    | ########## | 100%
anyio-3.3.4          | 149 KB    | ########## | 100%
libgd-2.3.3          | 459 KB    | ########## | 100%
pandas-1.3.4         | 11.1 MB   | ########## | 100%
future-0.18.2        | 734 KB    | ########## | 100%
pyqtchart-5.12       | 208 KB    | ########## | 100%
threadpoolctl-3.0.0  | 17 KB     | ########## | 100%
jedi-0.18.1          | 994 KB    | ########## | 100%
jpeg-9d              | 366 KB    | ########## | 100%
importlib_resources- | 21 KB     | ########## | 100%
smmap-3.0.5          | 22 KB     | ########## | 100%
font-ttf-source-code | 684 KB    | ########## | 100%
openjpeg-2.4.0       | 238 KB    | ########## | 100%
gitdb-4.0.9          | 46 KB     | ########## | 100%
websocket-client-1.2 | 74 KB     | ########## | 100%
pysocks-1.7.1        | 28 KB     | ########## | 100%
m2w64-gmp-6.1.0      | 726 KB    | ########## | 100%
tqdm-4.62.3          | 80 KB     | ########## | 100%
qt-5.12.9            | 106.1 MB  | ########## | 100%
m2w64-gcc-libgfortra | 342 KB    | ########## | 100%
ipykernel-6.5.0      | 178 KB    | ########## | 100%
setuptools-59.1.1    | 1020 KB   | ########## | 100%
pyrsistent-0.18.0    | 86 KB     | ########## | 100%
graphviz-2.49.3      | 1.1 MB    | ########## | 100%
ucrt-10.0.20348.0    | 1.2 MB    | ########## | 100%
libblas-3.9.0        | 4.5 MB    | ########## | 100%
jupyterlab_widgets-1 | 130 KB    | ########## | 100%
gettext-0.19.8.1     | 4.9 MB    | ########## | 100%
tk-8.6.11            | 3.8 MB    | ########## | 100%
python_abi-3.8       | 4 KB      | ########## | 100%
six-1.15.0           | 14 KB     | ########## | 100%
requests-2.26.0      | 52 KB     | ########## | 100%
bleach-4.1.0         | 121 KB    | ########## | 100%
m2w64-gcc-libs-5.3.0 | 520 KB    | ########## | 100%
matplotlib-inline-0. | 11 KB     | ########## | 100%
fribidi-1.0.10       | 63 KB     | ########## | 100%
importlib-metadata-4 | 33 KB     | ########## | 100%
gts-0.7.6            | 188 KB    | ########## | 100%
liblapacke-3.9.0     | 4.5 MB    | ########## | 100%
py-xgboost-1.4.2     | 141 KB    | ########## | 100%
lerc-3.0             | 140 KB    | ########## | 100%
libclang-11.1.0      | 20.8 MB   | ########## | 100%
xorg-libxau-1.0.9    | 57 KB     | ########## | 100%
vs2015_runtime-14.29 | 1.3 MB    | ########## | 100%
pywinpty-1.1.6       | 185 KB    | ########## | 100%
scipy-1.7.2          | 24.6 MB   | ########## | 100%
ftfy-6.0.3           | 50 KB     | ########## | 100%
ca-certificates-2021 | 176 KB    | ########## | 100%
msys2-conda-epoch-20 | 3 KB      | ########## | 100%
libpng-1.6.37        | 724 KB    | ########## | 100%
libprotobuf-3.18.1   | 2.3 MB    | ########## | 100%
testpath-0.5.0       | 86 KB     | ########## | 100%
zipp-3.6.0           | 12 KB     | ########## | 100%
sqlite-3.36.0        | 1.2 MB    | ########## | 100%
vc-14.2              | 13 KB     | ########## | 100%
numpy-1.19.5         | 4.9 MB    | ########## | 100%
idna-3.1             | 52 KB     | ########## | 100%
pixman-0.40.0        | 482 KB    | ########## | 100%
pandoc-2.16.1        | 17.8 MB   | ########## | 100%
font-ttf-inconsolata | 94 KB     | ########## | 100%
kiwisolver-1.3.2     | 59 KB     | ########## | 100%
xorg-libxt-1.2.1     | 811 KB    | ########## | 100%
m2w64-gcc-libs-core- | 214 KB    | ########## | 100%
pyglet-1.5.16        | 1.5 MB    | ########## | 100%
jinja2-3.0.3         | 99 KB     | ########## | 100%
prompt-toolkit-3.0.2 | 249 KB    | ########## | 100%
debugpy-1.5.1        | 3.2 MB    | ########## | 100%
cffi-1.15.0          | 229 KB    | ########## | 100%
font-ttf-ubuntu-0.83 | 1.9 MB    | ########## | 100%
jasper-2.0.33        | 677 KB    | ########## | 100%
cairo-1.16.0         | 2.3 MB    | ########## | 100%
pyqt-5.12.3          | 22 KB     | ########## | 100%
tbb-2021.4.0         | 149 KB    | ########## | 100%
send2trash-1.8.0     | 17 KB     | ########## | 100%
pyzmq-22.3.0         | 463 KB    | ########## | 100%
backports.functools_ | 9 KB      | ########## | 100%
ipython_genutils-0.2 | 21 KB     | ########## | 100%
traitlets-5.1.1      | 82 KB     | ########## | 100%
harfbuzz-3.1.1       | 921 KB    | ########## | 100%
wcwidth-0.2.5        | 33 KB     | ########## | 100%
nbformat-5.1.3       | 47 KB     | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok

done
Installing pip dependencies: ...working... Pip subprocess error:
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\thoma\.conda\envs\tf2\lib\http\client.py", line 459, in read
    n = self.readinto(b)
  File "C:\Users\thoma\.conda\envs\tf2\lib\http\client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\thoma\.conda\envs\tf2\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\thoma\.conda\envs\tf2\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\thoma\.conda\envs\tf2\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\cli\base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\commands\install.py", line 338, in run
    requirement_set = resolver.resolve(
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 482, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 349, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 201, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 281, in __init__
    super().__init__(
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 292, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\operations\prepare.py", line 482, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\operations\prepare.py", line 527, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\operations\prepare.py", line 213, in unpack_url
    file = get_http_url(
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\operations\prepare.py", line 94, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\network\download.py", line 145, in __call__
    for chunk in chunks:
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\cli\progress_bars.py", line 144, in iter
    for x in it:
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\thoma\.conda\envs\tf2\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\thoma\.conda\envs\tf2\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

Ran pip subprocess with arguments:
['C:\\Users\\thoma\\.conda\\envs\\tf2\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'D:\\02.ѧϰ\\7.▒▒▒▒ѧϰ\\handson-ml2-master\\condaenv.v9zkfmbv.requirements.txt']
Pip subprocess output:
Collecting tensorboard-plugin-profile~=2.5.0
  Downloading tensorboard_plugin_profile-2.5.0-py3-none-any.whl (1.1 MB)
Collecting tensorboard~=2.7.0
  Downloading tensorboard-2.7.0-py3-none-any.whl (5.8 MB)
Collecting tensorflow-addons~=0.14.0
  Downloading tensorflow_addons-0.14.0-cp38-cp38-win_amd64.whl (745 kB)
Collecting tensorflow-datasets~=4.4.0
  Downloading tensorflow_datasets-4.4.0-py3-none-any.whl (4.0 MB)
Collecting tensorflow-hub~=0.12.0
  Downloading tensorflow_hub-0.12.0-py2.py3-none-any.whl (108 kB)
Collecting tensorflow-probability~=0.14.1
  Downloading tensorflow_probability-0.14.1-py2.py3-none-any.whl (5.7 MB)
Collecting tensorflow-serving-api~=2.6.0
  Downloading tensorflow_serving_api-2.6.2-py2.py3-none-any.whl (37 kB)
Collecting tensorflow~=2.6.0
  Downloading tensorflow-2.6.2-cp38-cp38-win_amd64.whl (423.3 MB)

failed

CondaEnvException: Pip failed


```

And if you got an exception, please copy the full stacktrace here:

```stacktrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in inverse
ZeroDivisionError: division by zero
```

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/31619580/142384922-bfa984ee-62b8-4054-9476-1c83dba1bfea.png)

**Comment by ageron** [comment]
Hi @tms988 ,

This looks like a network error: if you start from the end of the stacktrace and work your way up, you see this:

* `CondaEnvException: Pip failed`: this means that conda failed at the last stage, after it successfully installed every conda package, while it was installing the pip packages. That's good news because it means that most of the packages are correctly installed.
* A few lines above, you can see: `pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.`. This is a timeout error, it means that the server did not reply, or not fast enough for the client. It may be due to a server problem, or a network issue, or perhaps your computer was on battery, and it went to sleep during the installation, and this stopped the WiFi connection. It could be many things.

So you should check that your network connection is doing ok, make sure your computer is not on battery and remains on during the installation (if that wasn't already the case), and try again.

**Comment by tms988** [comment]
Hi @ageron ，
Thank you very much for your reply, I followed your instructions and there are still problems; I am very sorry that I am a beginner, please forgive me for asking such a simple question; 

```
$ handson-ml2-master  conda env create -f environment.yml
CondaValueError: prefix already exists: C:\Users\thoma\.conda\envs\tf2
```

**Comment by ageron** [comment]
Ah, sorry about that: the first time you ran `conda env create -f environment.yml`, it partially created the `tf2` environment. So now that you run the command again, it complains that it already exists. The simplest solution is to delete the existing `tf2` environment like this:

```bash
conda env remove -n tf2
```

You can now check the list of environments:

```bash
conda env list
```

The `tf2` environment should not be there anymore.

Then make sure you have enough disk space: the full tf2 environment takes about 3GB. Also make sure your internet connection is nice and stable during the whole process, and your computer is plugged in (to avoid it going into sleep mode).

Then create the environment again:

```bash
conda env create -f environment.yml
```

I hope everything will work well this time. 🤞

**Comment by tms988** [comment]
God bless, it looks like it should be no problem this time. Thank you so much. I will start my machine learning journey. Your writing is great. 

![image](https://user-images.githubusercontent.com/31619580/143531558-7fb3af6e-3226-4d13-9f7e-82a71b0d2b6b.png)
