### ISSUE TITLE
Chapter 18: env.render() fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by mingqxu7** [ageron/handson-ml2#91]
I am hitting this issue on a VM running in the Azure cloud: 

(tf2) mingqxu@rl:~/handson-ml2$ uname -a
Linux rl 5.0.0-1027-azure #29~18.04.1-Ubuntu SMP Mon Nov 25 21:18:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

(tf2) mingqxu@rl:~/handson-ml2$ cat render.py
import gym

env = gym.make('CartPole-v1')
env.seed(42)
obs = env.reset()
try:
    import pyvirtualdisplay
    display = pyvirtualdisplay.Display(visible=0, size=(1400, 900)).start()
except ImportError:
    pass

env.render()
env.close()

(tf2) mingqxu@rl:~/handson-ml2$ python render.py
xdpyinfo was not found, X start can not be checked! Please install xdpyinfo!
Traceback (most recent call last):
  File "render.py", line 12, in <module>
    env.render()
  File "/home/mingqxu/anaconda3/envs/tf2/lib/python3.7/site-packages/gym/core.py", line 235, in render
    return self.env.render(mode, **kwargs)
  File "/home/mingqxu/anaconda3/envs/tf2/lib/python3.7/site-packages/gym/envs/classic_control/cartpole.py", line 150, in render
    from gym.envs.classic_control import rendering
  File "/home/mingqxu/anaconda3/envs/tf2/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/home/mingqxu/anaconda3/envs/tf2/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 221, in <module>
    from .xlib import XlibConfig as Config
  File "/home/mingqxu/anaconda3/envs/tf2/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 12, in <module>
    from pyglet.canvas.xlib import XlibCanvas
  File "/home/mingqxu/anaconda3/envs/tf2/lib/python3.7/site-packages/pyglet/canvas/__init__.py", line 103, in <module>
    from pyglet.canvas.xlib import XlibDisplay as Display
  File "/home/mingqxu/anaconda3/envs/tf2/lib/python3.7/site-packages/pyglet/canvas/xlib.py", line 19, in <module>
    from . import xlib_vidmoderestore
  File "/home/mingqxu/anaconda3/envs/tf2/lib/python3.7/site-packages/pyglet/canvas/xlib_vidmoderestore.py", line 23, in <module>
    from pyglet.libs.x11 import xlib
  File "/home/mingqxu/anaconda3/envs/tf2/lib/python3.7/site-packages/pyglet/libs/x11/xlib.py", line 2928, in <module>
    XEHeadOfExtensionList.argtypes = [XEDataObject]
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.

**Comment by ageron** [comment]
Thanks for your question, and sorry for the late response. Are you still experience it or did you find a solution?

I haven't personally run into this issue, but according to [this StackOverflow answer](https://stackoverflow.com/a/59908967/38626), it seems that it might be due to a bug in pyglet when using Python 3.7.6+, which was supposedly fixed in version 1.4.9. Unfortunately, according to this answer, gym is not yet compatible with the latest version of pyglet (perhaps this has been fixed since the answer was posted though).

So perhaps try updating pyglet and gym to the latest version, and if this does not fix the issue, try downgrading to Python 3.7.4.
